###   1) Write a program to create a 5 dimensional array with all zeros and ones

In [34]:
import numpy as np

In [35]:
np.zeros((1,1,1,5,4),dtype=int)

array([[[[[0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0]]]]])

In [33]:
np.ones((1,1,1,3,4),dtype=int)

array([[[[[1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1]]]]])

### 2) Write a program to create an array of 10 zeros,10 ones, and 10 fives in row 1 2 and 3 which create a new array of shape (3,10)

In [3]:
array3=np.array([np.zeros(10),np.ones(10),np.full(10,5)],dtype=int)
array3

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

### 3) Write a program to create a 3x4 matrix filled with values from 10 to 21.

In [4]:
array=np.arange(10,22)
array.reshape(3,4)

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

### 4) Write a  program to create a 10x10 zero matrix with elements on the main diagonal equal to 0,1,2,3,4,5,6,7,8,9

In [5]:
array1=np.diag([0,1,2,3,4,5,6,7,8,9])
array1

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 9]])

### 5)Write a program to create a 4x4 array. Create an array from below array by swapping first and last, second and third columns.

In [15]:
array1=np.arange(1,17).reshape(4,4)
array1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [16]:
array1[:,[0,-1]]=array1[:,[-1,0]]
array1[:,[1,2]]=array1[:,[2,1]]
array1

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9],
       [16, 15, 14, 13]])

### 6) Write a program to reverse an array (the first element becomes the last).Given array: [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 ]

In [8]:
array2=np.arange(12,28)
array2[::-1]

array([27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12])

### 7) Write a program to access all the elements greater than 30 and less than 80 and multiples of 5 from an array of shape 10,10 .Elements range from 1 to 100

In [3]:
array=np.arange(1,101)
array.shape=(10,10)
array

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [6]:
array[(array>30)&(array<80)&(array%5==0)]

array([35, 40, 45, 50, 55, 60, 65, 70, 75])

### 8) Write a program to create a 2D array with 1 on the border and 0 inside.

In [11]:
array=np.ones((5,5),dtype=int)
array

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [12]:
array[1:4,1:4]=0
array

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

### 9) Write a program to create a checkerboard pattern .Don't use default array function

In [7]:
array1=np.zeros((8,8),dtype=int)
array1

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [8]:
array1[[0,0,0,0],[1,3,5,7]]=1
array1[[1,1,1,1],[0,2,4,6]]=1
array1[[2,2,2,2],[1,3,5,7]]=1
array1[[3,3,3,3],[0,2,4,6]]=1
array1[[4,4,4,4],[1,3,5,7]]=1
array1[[5,5,5,5],[0,2,4,6]]=1
array1[[6,6,6,6],[1,3,5,7]]=1
array1[[7,7,7,7],[0,2,4,6]]=1
array1

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

### 10) Write a program to find common values between two arrays.

In [41]:
array1=np.array([10,20,40,60,70])
array2=np.array([10,30,40,70,80])
np.intersect1d(array1,array2)

array([10, 40, 70])

In [43]:
x=np.array([[2,4,6],[8,10,12],[14,16,18]])
y=np.array([[3,6,9],[12,15,18],[2,3,4]])
l=[]
for i in x.flatten():
    for j in y.flatten():
        if i==j:
            l.append(i)
np.array(l)

array([ 2,  4,  6, 12, 18])

### 11) Write a program to create an array 2d array and then reshape into 1d array

In [9]:
array=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [10]:
array.reshape(16,)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

### 12) Write a user defined function for creating a 1 or 2d array from scratch without using array functions

In [18]:
def array1_2d(x):
    n=int(input("enter the dimension: "))
    s=len(x)
    if n==1:
        print("array({})".format(x))
    elif n==2:
        print("array([",end="")
        print("[{}]".format(x[0]))
        for y in range(1,s-1):
            print("       [{}]".format(x[y]))
        for y in range(s-1,s):
            print("       [{}]".format(x[y]),end="")
            print("])")
l=[]
k=int(input("enter no of elements: "))
for i in range(k):
    a=input("enter the element: ")
    l.append(a)
print(l)
array1_2d(l)

enter no of elements: 4
enter the element: 1,2,3
enter the element: 6,9,4
enter the element: 8,5,7
enter the element: 5,8,1
['1,2,3', '6,9,4', '8,5,7', '5,8,1']
enter the dimension: 2
array([[1,2,3]
       [6,9,4]
       [8,5,7]
       [5,8,1]])
