# 1) Solve the below problem by using only numpy on tip data set

In [1]:
import numpy as np

In [2]:
y=np.genfromtxt(r"C:\Users\hi\Downloads\tipsf.csv",delimiter=",",skip_header=1)
y

array([[  0.  ,  16.99,   1.01, ...,   1.  ,   0.  ,   2.  ],
       [  1.  ,  10.34,   1.66, ...,   1.  ,   0.  ,   3.  ],
       [  2.  ,  21.01,   3.5 , ...,   1.  ,   0.  ,   3.  ],
       ...,
       [241.  ,  22.67,   2.  , ...,   0.  ,   0.  ,   2.  ],
       [242.  ,  17.82,   1.75, ...,   0.  ,   0.  ,   2.  ],
       [243.  ,  18.78,   3.  , ...,   2.  ,   0.  ,   2.  ]])

### 1) what is the total bill value?

In [3]:
a=np.sum(y[:,1])
print("the total bill value:",a)

the total bill value: 4827.77


### 2) what is the total tip value?

In [4]:
b=np.sum(y[:,2])
print("the total tip value:",b)

the total tip value: 731.5799999999999


### 3) count how many sun, sat, thu, fri are there?

In [7]:
f=y[:,5]
day,count=np.unique(f,return_counts=True)

In [17]:
print("no of sundays:",count[0])
print("no of saturdays:",count[1])
print("no of thursdays:",count[2])
print("no of fridays:",count[3])

no of sundays: 87
no of saturdays: 76
no of thursdays: 62
no of fridays: 19


### 4) how many smokers are there?

In [21]:
g=y[:,4]
total,smokers=np.unique(g,return_counts=True)

In [22]:
print("no of smokers:",smokers[1])

no of smokers: 93


### 5) what is the average tip given by male and female?

In [30]:
h=np.mean(y[:,2].take(np.where(y[:,3]==0)))
print("the average female tip:",h)

the average female tip: 2.8334482758620685


In [31]:
i=np.mean(y[:,2].take(np.where(y[:,3]==1)))
print("the average male tip:",i)

the average male tip: 3.0896178343949043


### 6)how much amount have been spent by female and male?

In [32]:
j=np.sum(y[:,1].take(np.where(y[:,3]==0)))
print("total amount spent by female:",j)

total amount spent by female: 1570.9499999999996


In [33]:
k=np.sum(y[:,1].take(np.where(y[:,3]==1)))
print("total amount spent by male:",k)

total amount spent by male: 3256.8199999999997


### 7) what is max and min tip given?

In [14]:
c=np.max(y[:,2])
d=np.min(y[:,2])
print("the max tip given:",c)
print()
print("the min tip given:",d)

the max tip given: 10.0

the min tip given: 1.0


### 8) how many male and female going for lunch and dinner?

In [38]:
l,m=np.unique(y[:,3].take(np.where(y[:,6]==0)),return_counts=True)
print("total male going for lunch:",m[1])
print("total female going for lunch:",m[0])

total male going for lunch: 124
total female going for lunch: 52


In [40]:
n,p=np.unique(y[:,3].take(np.where(y[:,6]==1)),return_counts=True)
print("total male going for dinner:",p[1])
print("total female going for dinner:",p[0])

total male going for dinner: 33
total female going for dinner: 35


### 9) find out the avg size?

In [15]:
e=np.mean(y[:,-1])
print("the avg size is:",e)

the avg size is: 2.569672131147541


### 10) how many male smokers are there and female smokers are there?

In [45]:
q,s=np.unique(y[:,4].take(np.where(y[:,3]==0)),return_counts=True)
print("female smokers are:",s[1])

female smokers are: 33


In [47]:
r,t=np.unique(y[:,4].take(np.where(y[:,3]==1)),return_counts=True)
print("male smokers are:",t[1])

male smokers are: 60


# 2) Solve the below problem by using only numpy functions on the  below given data set

In [2]:
import numpy as np

In [3]:
x=np.genfromtxt(r"C:\Users\hi\Downloads\train_extended.csv",delimiter=",",skip_header=1)

In [4]:
x

array([[ 1.575     ,  1.225     ,  0.375     , ...,  6.3219385 ,
         9.63883   , 10.        ],
       [ 1.2375    ,  1.        ,  0.375     , ...,  3.798833  ,
         7.654365  , 19.        ],
       [ 1.45      ,  1.1625    ,  0.4125    , ...,  7.01650125,
         7.257472  , 11.        ],
       ...,
       [ 1.125     ,  0.9125    ,  0.2875    , ...,  1.984465  ,
         3.118445  ,  7.        ],
       [ 1.625     ,  1.275     ,  0.4125    , ...,  7.86698625,
        10.489315  , 11.        ],
       [ 1.5875    ,  1.25      ,  0.3875    , ...,  7.38504475,
         8.788345  , 11.        ]])

### 1) what is the max and min length?

In [5]:
a=np.max(x[:,0])
b=np.min(x[:,0])
print("the max length:",a)
print()
print("the min length:",b)

the max length: 7.58349125

the min length: 0.0


### 2) find out the differnece between max and min length?

In [17]:
def max_min(x):
    return np.max(x)-np.min(x)

In [18]:
c=np.apply_along_axis(max_min,0,x[:,0])
print("the difference between max & min length:",c)

the difference between max & min length: 7.58349125


### 3) find column wise average?

In [17]:
d=np.mean(x,axis=0)
print("the column wise average:")
d

the column wise average:


array([ 1.31244808,  1.02032036,  0.34602787, 23.12343631,  9.98937025,
        4.99318096,  6.63422915,  9.950615  ])

### 4) find out all the age whose height is greater than 0.4?

In [30]:
w=x[x[:,2]>0.4]
print("the height greater than 0.4")
w

the height greater than 0.4


array([[ 1.45      ,  1.1625    ,  0.4125    , ...,  7.01650125,
         7.257472  , 11.        ],
       [ 1.525     ,  1.1875    ,  0.4375    , ...,  7.98038425,
         9.2135875 , 14.        ],
       [ 1.625     ,  1.2875    ,  0.4375    , ...,  8.66077225,
        11.3398    , 13.        ],
       ...,
       [ 1.6875    ,  1.3125    ,  0.425     , ...,  8.57572375,
        11.4815475 , 11.        ],
       [ 1.8125    ,  1.275     ,  0.4375    , ...,  9.979024  ,
        11.60912025, 11.        ],
       [ 1.625     ,  1.275     ,  0.4125    , ...,  7.86698625,
        10.489315  , 11.        ]])

In [32]:
print("persons age whose height > 0.4:")
w[:,-1]

persons age whose height > 0.4:


array([11., 14., 13., ..., 11., 11., 11.])

In [27]:
np.unique(w[:,-1],return_counts=True)

(array([ 5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16., 17.,
        18., 19., 20., 21., 22., 23., 24., 25., 26., 27., 29.]),
 array([    1,    11,    42,  1166,  6542, 10562, 11803,  6074,  5058,
         3150,  2453,  2028,  1764,  1373,  1067,   954,   477,   249,
          262,    89,    48,    39,    75,    49], dtype=int64))

### 5) what is average height & weight of the persons whose age is 10?

In [20]:
z=x[x[:,-1]==10]
z

array([[ 1.575     ,  1.225     ,  0.375     , ...,  6.3219385 ,
         9.63883   , 10.        ],
       [ 1.4875    ,  1.1875    ,  0.4       , ...,  7.66853975,
         8.50485   , 10.        ],
       [ 1.3375    ,  1.0125    ,  0.3375    , ...,  4.195726  ,
         5.953395  , 10.        ],
       ...,
       [ 1.5       ,  1.1625    ,  0.3125    , ...,  4.86193925,
         7.6827145 , 10.        ],
       [ 1.5125    ,  1.2125    ,  0.3875    , ...,  7.427569  ,
         8.9300925 , 10.        ],
       [ 1.55      ,  1.2125    ,  0.3875    , ...,  7.01650125,
         9.2135875 , 10.        ]])

In [22]:
s=np.mean(z[:,2])
p=np.mean(z[:,3])
print("the average height of persons of age 10:",s)
print()
print("the average weight of persons of age 10:",p)

the average height of persons of age 10: 0.3833672856539947

the average weight of persons of age 10: 28.243308450511314


### 6) what is the total shell weight?

In [28]:
f=np.sum(x[:,-2])
print("the total shell weight is:")
f

the total shell weight is:


1326845.8295214002

### 7) how many persons belongs to each and every unique age?

In [37]:
g=np.unique(x[:,-1],return_counts=True)
print("persons belongs to each and every unique age:")
g

persons belongs to each and every unique age:


(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
        27., 29.]),
 array([   46,    42,   625,  2787,  5475, 12450, 18276, 26818, 32906,
        30803, 23457, 12717, 10037,  6352,  4831,  3191,  2705,  1953,
         1591,  1206,   721,   296,   352,   110,    51,    46,    99,
           57], dtype=int64))

### 8) what is the difference between Shucked Weight and Viscera Weight?

In [9]:
#shucked weight
i=(x[:,4])
#viscera weight
j=(x[:,-3])
print("the difference b/w shucked weight & viscera weight:")
i-j

the difference b/w shucked weight & viscera weight:


array([5.9817445, 3.855532 , 4.1106775, ..., 2.9199985, 5.329706 ,
       9.8372765])

### 9) what is the average height of the persons whose age is between 14 & 19?

In [35]:
q=x[(x[:,-1]>14) & (x[:,-1]<19)]
print("persons age between 14 & 19:")
q

persons age between 14 & 19:


array([[ 1.275     ,  1.        ,  0.3875    , ...,  5.85417175,
         6.9456275 , 16.        ],
       [ 1.425     ,  1.15      ,  0.3625    , ...,  5.8683465 ,
         7.5126175 , 17.        ],
       [ 1.5625    ,  1.1625    ,  0.4       , ...,  5.85417175,
         9.355335  , 15.        ],
       ...,
       [ 1.3       ,  1.        ,  0.35      , ...,  4.89028875,
         7.37087   , 15.        ],
       [ 1.8       ,  1.45      ,  0.4375    , ..., 11.566596  ,
        17.56251525, 16.        ],
       [ 1.4375    ,  1.125     ,  0.375     , ...,  5.10291   ,
         7.087375  , 15.        ]])

In [38]:
j=np.mean(q[:,2])
print("avg height of persons with age b/w 14 & 19:")
j

avg height of persons with age b/w 14 & 19:


0.4190701892744479

### 10) what is the average weight if we include Shucked Weight, Viscera Weight & Shell Weight?

In [7]:
n=np.mean(x[:,3:7])
print("the average weight of all:")
n

the average weight of all:


11.185054166346786